export enum ContractTypes {
  Denominational,
  InterDivision,
  InterUnion,
  MissionaryService,
  RetiredWorkerService,
  Contract,
  VoluntaryAdventistService,
  HourlyTeacher,
  SocialService,
  HospitalLaCarlota,
  Others,
  DaycareMisAmiguitos,
  Unknown,
}